- Fixed compiling errors 	- Fixed spelling errors in the dispatcher-servlet that were causing bean initializing errors 	- Added setters in BrowseController, OrderController and BrowseServiceImpl to match dispatcher-servlet config 	- Removed duplicate mapping in spring-hibernate 	- Commented out AbstractController from BrowseController and OrderController to solve java.lang.NoClassDefFoundError error